WINDOW_WIDTH_RATIO = 0.13
WINDOW_HEIGHT_RATIO = 0.13
WINDOW_X_RATIO = 0.05
WINDOW_Y_RATIO = 0.05
LOADING_FONT = ("Helvetica", 99, "bold")
NUMBER_FONT = ("Helvetica", 255, "bold")
BG_COLOR = "#1B1212"
TEXT_COLOR = "white"
LOADING_ANIMATIONS = ['.', '..', '...', '....']
LOADING_UPDATE_INTERVAL = 250  # milliseconds
INPUT_BUFFER_MAX_LENGTH = 2
INPUT_RESET_TIMEOUT = 3.0  # seconds
DEFAULT_CHANNEL_INDEX = 2
CHANNEL_INFO_FONT = ("Helvetica", 99, "bold")
CHANNEL_INFO_DISPLAY_DURATION = 5000  # milliseconds
LOCAL_CHANNEL_DIRECTORIES = {
    0: "/home/melo/Videos/italian"
}
MPV_TIMESTAMP_FILENAME = "mpv-timestamp.txt"